server: 
  port: 9014
spring: 
  application:  
    name: tensquare-user-crawler #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.133:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
redis:
  host: 192.168.66.133
avatar:
  savepath: e:/webmagic/avatar
